version: '3'

services:
  php:
    build: 
      context: ./src/backend
    volumes:
      - ./src/backend:/var/www
      - ./local/php.ini:/usr/local/etc/php/conf.d/docker-vars.ini
      - ./local/nginx.conf:/etc/nginx/sites-available/default.conf
      - ./local/php_www.conf:/usr/local/etc/php-fpm.d/www.conf
    environment: 
      WEBROOT: "/var/www/backend/web"
      ENABLE_XDEBUG: 1
      XDEBUG_CONFIG: 192.168.1.70
      PHP_IDE_CONFIG: "serverName=stickers"
    ports:
      - 80:80
      - 8080:8080
    depends_on:
      - mysql

  frontend:
    image: node:10.13
    command: bash -c "cd /app && npm run devserver"
    extra_hosts:
      - "stickers.loc:127.0.0.1"
    ports:
      - 8090:8090
    volumes:
      - ./src/frontend:/app

  mysql:
    image: mariadb:10.1.43
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql
